// data.ts
import { Serie } from './Serie';

export const series = [
    new Serie(1, "Mr. Robot", "USA Network", 4, "Mr. Robot follows Elliot Alderson, a young man living in New York City, who works at the cyber security company Allsafe as a cybersecurity engineer. Alderson suffers from social anxiety disorder and clinical depression. He connects with people by hacking them, which often leads him to act as a cyber-vigilante. He is recruited by a mysterious insurrectionary anarchist known as Mr. Robot and joins his team of hacktivists known as fsociety. One of their missions is to cancel all consumer debt by destroying the data of one of the largest corporations in the world, E Corp (which Elliot perceives as Evil Corp), which also happens to be Allsafe's biggest client.", "https://www.usanetwork.com/mrrobot", "https://i.imgur.com/example1.jpg"),
    new Serie(2, "Shameless", "Showtime", 11, "Shameless is an American comedy-drama television series developed by John Wells that debuted on Showtime on January 9, 2011. It is a remake of the British series of the same name created by Paul Abbott, and is set in Chicago. The series depicts the dysfunctional family of Frank Gallagher, a single father raising six children. While he spends his days drunk, his kids learn to take care of themselves.", "https://www.sho.com/shameless", "https://i.imgur.com/example2.jpg"),
    new Serie(3, "Game of Thrones","HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones","https://i.imgur.com/TDCEV1S.jpg"),
    new Serie(4, "Futurama", "Fox", 7, "Futurama is an American animated science fiction sitcom created by Matt Groening that aired on Fox from March 28, 1999, to August 10, 2003, and on Comedy Central from March 23, 2008, to September 4, 2013. The series follows the adventures of slacker Philip J. Fry, who is cryogenically preserved for 1000 years and is revived in the 31st century. Fry finds work at an interplanetary delivery company, working alongside the one-eyed Turanga Leela and robot Bender Bending Rodriguez.", "https://www.hulu.com/series/futurama-79f2ccf6-8f99-4baf-87c4-97efdcfeb0a9", "https://i.imgur.com/example4.jpg"),
    new Serie(5, "Gravity Falls", "Disney Channel", 2, "Gravity Falls is an American animated mystery comedy television series produced by Disney Television Animation for Disney Channel and Disney XD from June 15, 2012, to February 15, 2016. The series follows the adventures of Dipper Pines (voiced by Jason Ritter) and his twin sister Mabel (voiced by Kristen Schaal) who are sent to spend the summer with their great-uncle (or 'Grunkle') Stan (voiced by series creator Alex Hirsch) in Gravity Falls, Oregon, a mysterious town full of paranormal forces and supernatural creatures.", "https://watchdisneychannel.go.com/gravity-falls", "https://i.imgur.com/example5.jpg"),
];
